In [ ]:
import numpy as np

In [ ]:
def forwardAlgorithm(obs, a, b, pi):
  """
  :param obs: Observation Vector
  :param a: Transition probability matrix
  :param b: Output probability matrix
  :param pi: Initial state probability vector
  :return: The Forward probability
  Instructions: Implement algorithm on slide 29 "The Forward Algorithm" of
  lecture note slides
  """
  # Tell Numpy how to print the array
  np.set_printoptions(formatter={'float': '{: 0.4f}'.format})

  # Initialization step
  print('\033[1m' + 'Initialization' + '\033[0m')

  # Initialize alpha to zero using numpy zeros function
  alpha=np.zeros((obs.shape[0], a.shape[0]))

  alpha[0, :]= pi * b[:, obs[0]]
  print()
  print(alpha)
  print()

  # The Induction Step
  print('\033[1m' + 'Induction' + '\033[0m')
  for t in range(1, obs.shape[0]):
    for j in range(a.shape[0]):
      alphaSum= 0.0
      for i in range(a.shape[0]):
        alphaSum+= alpha[t-1, i] * a[i, j]

      alpha[t, j] = alphaSum * b[j, obs[t]]
      print("alpha(", t+1, ",", j+1, ")")

      print(alpha)
      print()

  # The Termination Step
  print('\033[1m' + 'Termination' + '\033[0m')
  forwardProb=0
  forwardProb= np.sum(alpha[obs.shape[0] -1, :])
  return forwardProb

In [ ]:
def main():
  # Observations
  observationVector=np.array((0, 0, 1, 0, 1))
  # Transition Probabilities
  transitionProbMat=np.array(((0.2, 0.8), (0.6, 0.4)))
  # Output Probabilities
  outputProbMat=np.array(((0.7, 0.4), (0.3, 0.6)))
  # Initial state probability probability vector
  InitialStateProbVec=np.array((1.0, 0.0))
  # Invoke the Forward algorithm
  forwardProb=forwardAlgorithm(observationVector, transitionProbMat,
  outputProbMat, InitialStateProbVec)
  print(f'P(O|\u03BB)={forwardProb:1.4f}')


In [ ]:
if __name__ == "__main__":
    main()

Initialization

[[ 0.7000  0.0000]
 [ 0.0000  0.0000]
 [ 0.0000  0.0000]
 [ 0.0000  0.0000]
 [ 0.0000  0.0000]]

Induction
alpha( 2 , 1 )
[[ 0.7000  0.0000]
 [ 0.0980  0.0000]
 [ 0.0000  0.0000]
 [ 0.0000  0.0000]
 [ 0.0000  0.0000]]

alpha( 2 , 2 )
[[ 0.7000  0.0000]
 [ 0.0980  0.1680]
 [ 0.0000  0.0000]
 [ 0.0000  0.0000]
 [ 0.0000  0.0000]]

alpha( 3 , 1 )
[[ 0.7000  0.0000]
 [ 0.0980  0.1680]
 [ 0.0482  0.0000]
 [ 0.0000  0.0000]
 [ 0.0000  0.0000]]

alpha( 3 , 2 )
[[ 0.7000  0.0000]
 [ 0.0980  0.1680]
 [ 0.0482  0.0874]
 [ 0.0000  0.0000]
 [ 0.0000  0.0000]]

alpha( 4 , 1 )
[[ 0.7000  0.0000]
 [ 0.0980  0.1680]
 [ 0.0482  0.0874]
 [ 0.0434  0.0000]
 [ 0.0000  0.0000]]

alpha( 4 , 2 )
[[ 0.7000  0.0000]
 [ 0.0980  0.1680]
 [ 0.0482  0.0874]
 [ 0.0434  0.0220]
 [ 0.0000  0.0000]]

alpha( 5 , 1 )
[[ 0.7000  0.0000]
 [ 0.0980  0.1680]
 [ 0.0482  0.0874]
 [ 0.0434  0.0220]
 [ 0.0088  0.0000]]

alpha( 5 , 2 )
[[ 0.7000  0.0000]
 [ 0.0980  0.1680]
 [ 0.0482  0.0874]
 [ 0.0434  0.0220]
 [